#!/bin/sh

export ENV="$HOME/.config/ash/ashrc"
export PATH="$PATH:$HOME/.local/bin"
export EDITRO="vim"
export HISTFILE="$HOME/.config/ash/ash_history"
export HISTFILESIZE=128

export GRIM_DEFAULT_DIR="$HOME/Pictures"
export MOZ_ENABLE_WAYLAND=1

export MESA_LOADER_DRIVER_OVERRIDE=crocus

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

export PS1="\w\$ "

# If running from tty1 start sway
if [ "$(tty)" = "/dev/tty1" ]; then
  exec dbus-run-session sway
fi

