#!/bin/sh

export ENV="$HOME/.config/ash/ashrc"
export PATH="$PATH:$HOME/.local/bin"
export EDITOR="vim"
export HISTFILE="$HOME/.config/ash/ash_history"
export HISTSIZE=127
export GRIM_DEFAULT_DIR="$HOME/Pictures"
export MOZ_ENABLE_WAYLAND=1

# note setting this can create problems. see ncurses(3)
export ESCDELAY=0

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

